name: Images scanner and assesment

on:
  workflow_dispatch:


jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Pull Docker Image
        run: docker pull debian:11

      - name: Docker Scout
        run: docker images
