# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Sbom/Vex scans and upload

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  scan:
    name: Scan projects
    runs-on: ubuntu-latest
    container: quay.io/pluribus_one/sbom_vex_scanner:latest
    strategy:
      matrix:
        prj_folder: ['vuln_apps/react-app', 'vuln_apps/dvna', 'vuln_apps/OWASPWebGoatPHP']

    steps:
    - uses: actions/checkout@v3
    - run: |
        cd {{ prj_folder }}
        cdxgen --format json -o "vuln_app_bom.json" --spec-version=1.4
        osv-scanner -S "vuln_app_bom.json" --format json  > "vuln_app_vex.json"
    - name: Archive code coverage results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: sbom-vex-jsons
        path: vuln_app_*.json
        retention-days: 5
